import { z } from 'zod'

/**
 * Schema for learner configuration generated by LLM
 *
 * Discriminated union on `type` — supports text and list learners.
 * This represents what Brain's prompt decomposition outputs.
 * Excludes runtime config like model.
 */

const baseLearnerFields = {
	id: z.string().describe('Unique identifier for this learner (kebab-case)'),
	name: z.string().describe('Human-readable display name'),
	description: z
		.string()
		.describe(
			'Brief description of what this learner tracks, used for query routing',
		),
	instructions: z
		.string()
		.describe(`Full structured instructions following the format:
[Core understanding directive]

Watch for:
- [Specific condition 1]
- [Specific condition 2]

Track answers to:
- [Question 1]
- [Question 2]`),
	focus: z
		.string()
		.optional()
		.describe('Optional focus areas to narrow observation filtering'),
}

const textLearnerConfigSchema = z.object({
	...baseLearnerFields,
	type: z
		.literal('text')
		.describe(
			'Text learner — builds narrative prose understanding. Best for qualitative patterns, preferences, philosophies, and interconnected concepts.',
		),
	maintenance: z
		.object({
			strategy: z
				.enum(['continuous', 'cumulative', 'decay'])
				.describe(
					'How understanding evolves: continuous (single growing text), cumulative (summarize when large), decay (recent items weighted higher)',
				),
		})
		.describe(
			'Maintenance configuration. Use { strategy: "continuous" } as default.',
		),
})

const listLearnerConfigSchema = z.object({
	...baseLearnerFields,
	type: z
		.literal('list')
		.describe(
			'List learner — tracks a structured collection of items. Best for entities, catalogs, inventories, preferences as discrete items, and anything countable.',
		),
	listGovernance: z
		.object({
			deduplication: z
				.enum(['strict', 'none'])
				.optional()
				.describe(
					'How to handle duplicate items. Default: strict.',
				),
			maxItems: z
				.number()
				.optional()
				.describe(
					'Maximum number of items before pruning kicks in. Default: 200.',
				),
			pruning: z
				.enum(['oldest', 'least-confident', 'none'])
				.optional()
				.describe(
					'How to prune when maxItems exceeded. Default: oldest.',
				),
		})
		.optional()
		.describe('List-specific governance settings. Defaults are sensible — omit unless specific needs.'),
})

export const learnerConfigSchema = z.discriminatedUnion('type', [
	textLearnerConfigSchema,
	listLearnerConfigSchema,
])

export type GeneratedLearnerConfig = z.infer<typeof learnerConfigSchema>
