import { z } from 'zod'

/**
 * Schema for learner configuration generated by LLM
 *
 * This represents what Brain's prompt decomposition outputs.
 * It's a subset of TextLearnerConfig — excludes runtime config like model.
 */
export const learnerConfigSchema = z.object({
	id: z.string().describe('Unique identifier for this learner (kebab-case)'),
	name: z.string().describe('Human-readable display name'),
	description: z
		.string()
		.describe(
			'Brief description of what this learner tracks, used for query routing',
		),
	instructions: z
		.string()
		.describe(`Full structured instructions following the format:
[Core understanding directive]

Watch for:
- [Specific condition 1]
- [Specific condition 2]

Track answers to:
- [Question 1]
- [Question 2]`),
	type: z
		.literal('text')
		.describe('Learner type - must be "text"'),
	maintenance: z
		.object({
			strategy: z
				.enum(['continuous', 'cumulative', 'decay'])
				.describe(
					'How understanding evolves: continuous (single growing text), cumulative (summarize when large), decay (recent items weighted higher)',
				),
		})
		.describe(
			'Maintenance configuration. Use { strategy: "continuous" } as default.',
		),
})

export type GeneratedLearnerConfig = z.infer<typeof learnerConfigSchema>
