import { z } from 'zod'

/**
 * Schema for learner configuration generated by LLM decomposition.
 *
 * Flat object — no discriminated unions (oneOf breaks OpenAI + Gemini structured output).
 * Governance is excluded — applied as defaults at learner creation time.
 */
export const learnerConfigSchema = z.object({
	id: z.string().describe('Unique identifier for this learner (kebab-case)'),
	name: z.string().describe('Human-readable display name'),
	description: z
		.string()
		.describe(
			'Brief description of what this learner tracks, used for query routing',
		),
	instructions: z
		.string()
		.describe(`Full structured instructions following the format:
[Core understanding directive]

Watch for:
- [Specific condition 1]
- [Specific condition 2]

Track answers to:
- [Question 1]
- [Question 2]`),
	focus: z
		.string()
		.optional()
		.describe('Optional focus areas to narrow observation filtering'),
	type: z
		.enum(['text', 'list'])
		.describe(
			'Learner type. "text" — builds narrative prose understanding, best for qualitative patterns, preferences, philosophies. "list" — tracks a structured collection of items, best for entities, catalogs, inventories.',
		),
})

/**
 * Full learner config type — extends LLM schema with optional governance
 * for programmatic use (explicit learners, evolution handlers, etc.).
 */
export type GeneratedLearnerConfig = z.infer<typeof learnerConfigSchema> & {
	governance?: Record<string, unknown>
}
