import { z } from 'zod'

/**
 * Schema for neuron configuration generated by LLM decomposition.
 *
 * Flat object — no discriminated unions (oneOf breaks OpenAI + Gemini structured output).
 * Governance is excluded — applied as defaults at neuron creation time.
 */
export const neuronConfigSchema = z.object({
	id: z.string().describe('Unique identifier for this neuron (kebab-case)'),
	name: z.string().describe('Human-readable display name'),
	description: z
		.string()
		.describe(
			'Brief description of what this neuron tracks, used for query routing',
		),
	instructions: z
		.string()
		.describe(`Full structured instructions following the format:
[Core understanding directive]

Watch for:
- [Specific condition 1]
- [Specific condition 2]

Track answers to:
- [Question 1]
- [Question 2]`),
	focus: z
		.string()
		.nullable()
		.describe('Optional focus areas to narrow observation filtering (null if none)'),
	type: z
		.enum(['text', 'list'])
		.describe(
			'Neuron type. "text" — builds narrative prose understanding, best for qualitative patterns, preferences, philosophies. "list" — tracks a structured collection of items, best for entities, catalogs, inventories.',
		),
})

/**
 * Full neuron config type — extends LLM schema with optional governance
 * for programmatic use (explicit neurons, evolution handlers, etc.).
 */
export type GeneratedNeuronConfig = z.infer<typeof neuronConfigSchema> & {
	governance?: Record<string, unknown>
	skipObservation?: boolean
	/** Custom observation schema — skips LLM generation when provided */
	observationSchema?: Record<string, unknown>
	/** Custom understanding schema — skips LLM generation when provided */
	understandingSchema?: Record<string, unknown>
}
